
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-03-15T00:01:01+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "b022a0aabcc6dbe2440244bf48d08fbb6ecdaf2d",
 "version": "0.2.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
